# Change these first
owner: Altair47 # Your GitHub organization or username, where this repository lives
repo: 3nt-upptime # The name of this repository

sites:
  - name: 3nitas
    url: https://3nitas.com
  - name: Afis
    url: https://afis.gr
  - name: Afis Kinigoi
    url: https://afis-kinigoi.gr
  - name: Alfa Beer
    url: https://alfabeer.gr
  - name: Antenna Group
    url: https://antenna-group.com
  - name: Antonis Fousas
    url: https://antonisfousas.gr
  - name: Arjuna Maritime
    url: https://arjunamaritime.id
  - name: Blinqme
    url: https://blinqme.com
  - name: Breast Imaging
    url: https://breastimaging.gr
  - name: Campari Passion
    url: https://camparipassion.gr
  - name: Elekap
    url: https://elekap.org
  - name: EOS Systems
    url: https://eos-systems.gr
  - name: Epsilon Hellas
    url: https://epsilonhellas.com
  - name: Epsilon Hellas Ukraine
    url: https://epsilonhellas.com.ua
  - name: Epsilon Odessa
    url: https://epsilonodessa.com.ua
  - name: Expedite
    url: https://expedite.gr
  - name: Fischer Beer
    url: https://fischerbeer.gr
  - name: Gerofinikas Boutique Hotel
    url: https://gerofinikasboutiquehotel.com
  - name: Hazmat
    url: https://hazmat.gr
  - name: IGI Poseidon
    url: https://igi-poseidon.com
  - name: Kore
    url: https://kore.gr
  - name: Let's Place
    url: https://letsplace.gr
  - name: Mail Delivery
    url: https://maildelivery.gr
  - name: Mamos
    url: https://mamos.gr
  - name: Milies Ilia's
    url: https://miliesilias.gr
  - name: MPD
    url: https://mpd.gr
  - name: Myritmeester
    url: https://myritmeester.nl
  - name: oseven
    url: https://oseven.io
  - name: OTE Academy
    url: https://oteacademy.gr
  - name: Papadopoulou
    url: https://papadopoulou.gr
  - name: Paradeigmatos Harin
    url: https://paradeigmatos-harin.gr
  - name: Pastel Yachting
    url: https://pastelyachting.gr
  - name: Primo Gusto
    url: https://primogusto.gr
  - name: Priority Cyprus 
    url: https://www.priority.com.cy
  - name: Priority Greece 
    url: https://www.priority.com.gr
  - name: Reach-Cheree
    url: https://reach-cheree.gr
  - name: Samaras Mining
    url: https://samarasmining.com
  - name: Sanola
    url: https://sanola.gr
  - name: Southbridge Partners
    url: https://southbridge-partners.com
  - name: The Circle Group App
    url: https://thecirclegroupapp.com
  - name: The Jungle Ad
    url: https://thejunglead.com
  - name: Three Cents
    url: https://threecents.com
  - name: 3Nitas
    url: https://threenitas.com
  - name: To Prasinóspiti
    url: https://toprasinospiti.gr
  - name: Tothama
    url: https://tothama.gr
  - name: Veritas MTC
    url: https://veritasmtc.com
  - name: VMG
    url: https://vmg.gr
  - name: White Coast
    url: https://whitecoast.gr
  - name: Alfa Beer
    url: https://www.alfabeer.gr
  - name: Priority
    url: https://www.priority.com.gr
  - name: Xriselia
    url: https://xriselia.gr
  - name: Zerris
    url: https://zerris.gr


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /3nt-upptime
  logoUrl: https://raw.githubusercontent.com/Altair47/3nt-upptime/master/assets/3ntas.svg
  name: Uptime Monitor
  introTitle: "Uptime monitor powered by Github Actions."
  introMessage: More info at (https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
